In [4]:
pwd

'/home/jovyan/grn experiments'

In [6]:
sys.path.insert(0, "grn-paper/src")


In [7]:
import sys
import pickle
import numpy as np
import pandas as pd
import networkx as nx

# Clone/download the authors' repository first
sys.path.insert(0, "grn-paper")

# Important for unpickling their custom GRN class
from grn import grn

with open("grns/graph.647.gpickle", "rb") as f:
    G = pickle.load(f)

beta = np.asarray(G.beta)

print(beta.shape)
print(G.number_of_nodes())
print(G.number_of_edges())
print(np.count_nonzero(beta))

(2000, 2000)
2000
6945
6846


In [8]:
beta

array([[-0.       , -2.9309707, -0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       , -0.       , -1.8825034, ...,  0.       ,  0.       ,
        -0.       ],
       [-1.1054038,  0.       , -0.       , ...,  0.       , -0.       ,
        -0.       ],
       ...,
       [ 0.       , -0.       ,  0.       , ...,  0.       ,  0.       ,
        -0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       , -0.       ,
         0.       ],
       [-0.       ,  0.       ,  0.       , ..., -0.       ,  0.       ,
        -0.       ]], shape=(2000, 2000), dtype=float32)

In [18]:
beta.sum(0)

array([-15.639813 ,  -3.5226014,   7.7951217, ...,   1.0862184,
        -1.07015  ,   1.0099255], shape=(2000,), dtype=float32)

In [20]:
beta.sum(1)

array([ -3.6896787,   6.552198 , -20.793863 , ...,   0.       ,
         0.       ,   0.       ], shape=(2000,), dtype=float32)

In [21]:
abs_beta = np.abs(beta)

In [26]:
abs_beta.sum(1)

array([110.87782, 255.46693,  95.31314, ...,   0.     ,   0.     ,
         0.     ], shape=(2000,), dtype=float32)

In [27]:
abs_beta.sum(0)

array([24.615532 , 25.050179 , 16.387432 , ...,  1.0862184,  1.07015  ,
        1.0099255], shape=(2000,), dtype=float32)